### ISSUE TITLE
Issue after Angular 9 upgrade

### ISSUE THREAD

**Issue by crooksey** [MurhafSousli/ngx-sharebuttons#429] opened 2020-02-07 11:24 UTC
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

No errors

#### What is the current behavior?

ERROR TypeError: Cannot read property 'shareButton' of undefined

#### What are the steps to reproduce?

<share-buttons [theme]="'modern-dark'"
                                             [include]="['facebook','twitter','linkedin','pinterest','whatsapp','email','copy']"
                                             [show]="5"
                                             [url]="currentURL">
                                         </share-buttons>

#### What is the use-case or motivation for changing an existing behavior?

Angular 9 support

#### Which versions are you using for the following packages?

Angular: 9
Angular CDK:9
Angular CLI:9.0.1
Angular-fontawesome: 0.5.0
Share buttons: 4.1.4

#### Is there anything else we should know?

Code was working fine in Angular 8, have checked documentation and code seems correct, cannot work our why since upgrading to 9.x this throws an error.

**Comment by AnkitSharma-007** [comment] 2020-02-09 09:21
I am also facing the same issue after updating to v9. The code was working on v8.

**Comment by MurhafSousli** [comment] 2020-02-09 23:17
This error is only thrown when using the packages `@ngx-share/button` and `@ngx-share/buttons`.

For now, you can use the share directive with angular 9 from the package `@ngx-share/core` without any problems.

I will release a new version in the upcoming days!

**Comment by AnkitSharma-007** [comment] 2020-02-10 07:45
How can we set up the custom config with `@ngx-share/core` 

This is my current implementation in `app.module.ts`
```
import { ShareButtonsModule } from '@ngx-share/buttons';

const customConfig: ShareButtonsConfig = {
  include: ['facebook', 'twitter', 'linkedin', 'reddit', 'whatsapp', 'telegram', 'print', 'email'],
  theme: 'circles-dark',
  autoSetMeta: true,
  twitterAccount: 'ankitsharma_007'
};

imports: [
    ShareButtonsModule.withConfig(customConfig),
]
```

Is it possible to change this using ```@ngx-share/core```.

**Comment by MurhafSousli** [comment] 2020-02-10 10:25
@AnkitSharma-007  Same way `ShareModule.withConfig(customConfig)`

**Comment by AnkitSharma-007** [comment] 2020-02-10 18:43
Yes this is working. Need to do some changes in the code.

Earlier :

app.module.ts

```
import { ShareButtonsModule } from '@ngx-share/buttons';

const customConfig: ShareButtonsConfig = {
  include: ['facebook', 'twitter', 'linkedin', 'reddit', 'whatsapp', 'telegram', 'print', 'email'],
  theme: 'circles-dark',
  autoSetMeta: true,
  twitterAccount: 'ankitsharma_007'
};

imports: [
    ShareButtonsModule.withConfig(customConfig),
]
```
component.html
```
<share-buttons></share-buttons>
```
Now:

app.module.ts

```
import { ShareButtonsConfig, ShareModule } from '@ngx-share/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';

const customConfig: ShareButtonsConfig = {
  autoSetMeta: true,
  twitterAccount: 'ankitsharma_007'
};

imports: [
   ShareModule.withConfig(customConfig),
]
```
component.html
```
<button mat-fab shareButton="facebook" [style.backgroundColor]="share.prop.facebook.color">
    <fa-icon [icon]="share.prop.facebook.icon" size="lg"></fa-icon>
</button>
<button mat-fab shareButton="twitter" [style.backgroundColor]="share.prop.twitter.color">
    <fa-icon [icon]="share.prop.twitter.icon" size="lg"></fa-icon>
</button>
<button mat-fab shareButton="linkedin" [style.backgroundColor]="share.prop.linkedin.color">
    <fa-icon [icon]="share.prop.linkedin.icon" size="lg"></fa-icon>
</button>
```
component.ts
```
import { ShareService } from '@ngx-share/core';
constructor(public share: ShareService) {  }

```
Here is my repo with working code in Angular 9

https://github.com/AnkitSharma-007/blogging-app-with-Angular-CloudFirestore

**Comment by crooksey** [comment] 2020-02-18 09:30
I have to agree, that when using @ngx-share/core although I can get it to work, the themes/styles do not apply in the same way. It would be helpful (if possible) to provide a working stackblitz using core.

**Comment by sameretto** [comment] 2020-02-20 02:17
@MurhafSousli  Any progress on this? Has this been resolved?

**Comment by yasminSalah** [comment] 2020-02-25 08:52
> Yes this is working. Need to do some changes in the code.
> 
> Earlier :
> 
> app.module.ts
> 
> ```
> import { ShareButtonsModule } from '@ngx-share/buttons';
> 
> const customConfig: ShareButtonsConfig = {
>   include: ['facebook', 'twitter', 'linkedin', 'reddit', 'whatsapp', 'telegram', 'print', 'email'],
>   theme: 'circles-dark',
>   autoSetMeta: true,
>   twitterAccount: 'ankitsharma_007'
> };
> 
> imports: [
>     ShareButtonsModule.withConfig(customConfig),
> ]
> ```
> 
> component.html
> 
> ```
> <share-buttons></share-buttons>
> ```
> 
> Now:
> 
> app.module.ts
> 
> ```
> import { ShareButtonsConfig, ShareModule } from '@ngx-share/core';
> import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
> 
> const customConfig: ShareButtonsConfig = {
>   autoSetMeta: true,
>   twitterAccount: 'ankitsharma_007'
> };
> 
> imports: [
>    ShareModule.withConfig(customConfig),
> ]
> ```
> 
> component.html
> 
> ```
> <button mat-fab shareButton="facebook" [style.backgroundColor]="share.prop.facebook.color">
>     <fa-icon [icon]="share.prop.facebook.icon" size="lg"></fa-icon>
> </button>
> <button mat-fab shareButton="twitter" [style.backgroundColor]="share.prop.twitter.color">
>     <fa-icon [icon]="share.prop.twitter.icon" size="lg"></fa-icon>
> </button>
> <button mat-fab shareButton="linkedin" [style.backgroundColor]="share.prop.linkedin.color">
>     <fa-icon [icon]="share.prop.linkedin.icon" size="lg"></fa-icon>
> </button>
> ```
> 
> component.ts
> 
> ```
> import { ShareService } from '@ngx-share/core';
> constructor(public share: ShareService) {  }
> ```
> 
> Here is my repo with working code in Angular 9
> 
> https://github.com/AnkitSharma-007/blogging-app-with-Angular-CloudFirestore

can u guide me in angular 8 how make it work

**Comment by FotoramaMX** [comment] 2020-02-27 19:01
This stop working since update to angular 9 too, but i have this issue:

`main.bdc9eac2d3e9e47d38c5.js:1 ERROR TypeError: Cannot read property 'prop' of undefined
    at Object.updateDirectives (12.516fb781619496a755f4.js:1)
    at Object.updateDirectives (main.bdc9eac2d3e9e47d38c5.js:1)
    at fb (main.bdc9eac2d3e9e47d38c5.js:1)
    at Sb (main.bdc9eac2d3e9e47d38c5.js:1)
    at wb (main.bdc9eac2d3e9e47d38c5.js:1)
    at fb (main.bdc9eac2d3e9e47d38c5.js:1)
    at Sb (main.bdc9eac2d3e9e47d38c5.js:1)
    at Cb (main.bdc9eac2d3e9e47d38c5.js:1)
    at fb (main.bdc9eac2d3e9e47d38c5.js:1)
    at Sb (main.bdc9eac2d3e9e47d38c5.js:1)`

Any Idea about this? 

Best!

**Comment by neaptolem** [comment] 2020-02-29 12:26
Hi @MurhafSousli do you need some help with resolving the issue?
It looks like it is a problem in ngx-button select ref with @ViewChild.

**Comment by MurhafSousli** [comment] 2020-02-29 19:24
@neaptolem I currently don't have an internet connection at home due to my relocation, if you can give me a fix PR. I can publish it from work.

**Comment by neaptolem** [comment] 2020-03-01 08:48
@MurhafSousli I try update project to Angular 9 version. But I don't have permission to push the branch with the update.

**Comment by xjose97x** [comment] 2020-03-02 15:13
@MurhafSousli when can we expect a fix for this issue?

Thanks for your great work!

**Comment by ThePatzen** [comment] 2020-03-09 18:09
@MurhafSousli i really like your work!! Thanks!

Looking forward to the new version!!

Best Regards,

David

**Comment by bjfisher-cbg** [comment] 2020-03-13 18:49
+1

**Comment by bjornharvold** [comment] 2020-03-17 11:32
@MurhafSousli Great project. Looking forward to Angular 9 support.

**Comment by fromage9747** [comment] 2020-03-18 04:05
tried doing it the new way because it does not have angular 9 support and all I get is this:

![image](https://user-images.githubusercontent.com/23147783/76924269-626a2600-6908-11ea-9ad8-6a399d589c3a.png)

**Comment by Josvds** [comment] 2020-03-20 05:52
+1

**Comment by fromage9747** [comment] 2020-03-20 06:12
+1

**Comment by iMrLopez** [comment] 2020-03-22 06:22
+1

**Comment by fromage9747** [comment] 2020-03-22 08:27
Grabbed the CSS from the module and used the example THML form Chrome dev tools to try and work around this but just get the below:

![image](https://user-images.githubusercontent.com/23147783/77245481-789e1c00-6c51-11ea-9cc0-2ecf5ff53484.png)

Twitter Icon is with all the classes and the Facebook icon is without.

**Comment by fromage9747** [comment] 2020-03-22 09:18
@neaptolem Please can you let me know what code changes you did to make this work.  I would like to apply them manually.  Cheers

**Comment by neaptolem** [comment] 2020-03-22 10:02
@fromage9747 I just updated the library to angular 9, but I still have problems with the build.

**Comment by fromage9747** [comment] 2020-03-22 10:03
@neaptolem What issues are you still having?

**Comment by neaptolem** [comment] 2020-03-22 10:10
@fromage9747 I have made fork https://github.com/neaptolem/ngx-sharebuttons
branch update-to-ng9

**Comment by fromage9747** [comment] 2020-03-22 10:12
@neaptolem Thanks!  I will give it a try later on today.

**Comment by iMrLopez** [comment] 2020-03-22 15:43
Can we get a PR with that fork please? @MurhafSousli

**Comment by Martin-Bee** [comment] 2020-03-29 13:11
Here is my [fork](https://github.com/Martin-Bee/ngx-sharebuttons/tree/angular.v9) based off @neaptolem that I got working with angular 9.1. 

Main issue was fixes adding viewChild {static: true} in @ngx-share/core/share-button.directive.ts and fixing some of the material imports. Bumped versions and enabled ivy.
Here is the compiled file against @angular/9.1 that were produced by npm run init-build && npm run build-all

I am using those files with @angular/9.1
package.json:
```
    "@ngx-share/button": "file:dist-share-buttons/button",
    "@ngx-share/buttons": "file:dist-share-buttons/buttons",
    "@ngx-share/core": "file:dist-share-buttons/core",
```

Module import
```
import { ShareButtonsModule } from 'dist-share-buttons/buttons';
import { ShareButtonModule } from 'dist-share-buttons/button';
... 
  imports: [CommonModule, FormsModule, FontAwesomeModule, ShareButtonsModule, ShareButtonModule],
```
[dist-share-buttons.zip](https://github.com/MurhafSousli/ngx-sharebuttons/files/4398917/dist-share-buttons.zip)

**Comment by davidtoral** [comment] 2020-04-07 09:41
How to install and use it with npm? @Martin-Bee @MurhafSousli

**Comment by fromage9747** [comment] 2020-04-07 09:51
@davidtoral 
I decided to wait for @MurhafSousli to merge and release version 8 as I couldn't get anything to work. 
https://github.com/MurhafSousli/ngx-sharebuttons/pull/432

So far there are some failures on the Travis build.

**Comment by MurhafSousli** [comment] 2020-04-07 11:08
I published a beta release, please install using `npm i ngx-sharebuttons@8.0.0-beta.1`, for now see the changelog on #432 . I will update the docs incrementally with time.

Here is a [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-v8?file=src/app/app.module.ts) using the latest beta version

**Comment by fromage9747** [comment] 2020-04-07 11:12
@MurhafSousli Thank you!

**Comment by Jrbebel** [comment] 2020-04-07 14:51
@MurhafSousli nice !!

**Comment by cervelliriccardo** [comment] 2020-04-09 07:30
this is the code part that raise an exception: ctx.ref.shareButton -> ctx.ref is undefined

ShareButton.ɵfac = function ShareButton_Factory(t) { return new (t || ShareButton)(ɵngcc0.ɵɵdirectiveInject(ɵngcc1.ShareService)); };
ShareButton.ɵcmp = ɵngcc0.ɵɵdefineComponent({ type: ShareButton, selectors: [["share-button"]], viewQuery: function ShareButton_Query(rf, ctx) { if (rf & 1) {
ɵngcc0.ɵɵviewQuery(ShareDirective, true);
} if (rf & 2) {
var _t;
ɵngcc0.ɵɵqueryRefresh(_t = ɵngcc0.ɵɵloadQuery()) && (ctx.ref = _t.first);
} }, hostVars: 2, hostBindings: function ShareButton_HostBindings(rf, ctx) { if (rf & 2) {
ɵngcc0.ɵɵclassMap(ctx.buttonClass);
} }, inputs: { showIcon: "showIcon", showText: "showText", showCount: "showCount", size: "size", theme: "theme", createButton: ["button", "createButton"], setUrl: ["url", "setUrl"], title: "title", description: "description", image: "image", tags: "tags", autoSetMeta: "autoSetMeta", text: "text", icon: "icon" }, outputs: { count: "count", opened: "opened", closed: "closed" }, decls: 6, vars: 19, consts: [[1, "sb-wrapper", 3, "shareButton", "url", "image", "title", "description", "tags", "autoSetMeta", "getCount", "count", "opened", "closed"], [1, "sb-inner"], [1, "sb-content"], ["class", "sb-icon", 4, "ngIf"], ["class", "sb-text", 4, "ngIf"], ["class", "sb-count", 4, "ngIf"], [1, "sb-icon"], [3, "icon", "fixedWidth"], [1, "sb-text"], [1, "sb-count"]], template: function ShareButton_Template(rf, ctx) { if (rf & 1) {
ɵngcc0.ɵɵelementStart(0, "button", 0);
ɵngcc0.ɵɵlistener("count", function ShareButton_Template_button_count_0_listener($event) { return ctx.onCount($event); })("opened", function ShareButton_Template_button_opened_0_listener($event) { return ctx.opened.emit($event); })("closed", function ShareButton_Template_button_closed_0_listener($event) { return ctx.closed.emit($event); });
ɵngcc0.ɵɵelementStart(1, "div", 1);
ɵngcc0.ɵɵelementStart(2, "div", 2);
ɵngcc0.ɵɵtemplate(3, ShareButton_div_3_Template, 2, 2, "div", 3);
ɵngcc0.ɵɵtemplate(4, ShareButton_div_4_Template, 2, 1, "div", 4);
ɵngcc0.ɵɵelementEnd();
ɵngcc0.ɵɵtemplate(5, ShareButton_div_5_Template, 4, 3, "div", 5);
ɵngcc0.ɵɵelementEnd();
ɵngcc0.ɵɵelementEnd();
} if (rf & 2) {
ɵngcc0.ɵɵstyleProp("font-size", (1 + ctx.size / 20) * 14, "px");
ɵngcc0.ɵɵclassProp("sb-show-icon", ctx.showIcon)("sb-show-text", ctx.showText)("sb-show-count", ctx.showCount && ctx.shareCount);
ɵngcc0.ɵɵproperty("shareButton", ctx.button)("url", ctx.url)("image", ctx.image)("title", ctx.title)("description", ctx.description)("tags", ctx.tags)("autoSetMeta", ctx.autoSetMeta)("getCount", ctx.showCount);
ɵngcc0.ɵɵadvance(3);
ɵngcc0.ɵɵproperty("ngIf", ctx.showIcon && ctx.ref.shareButton);
ɵngcc0.ɵɵadvance(1);
ɵngcc0.ɵɵproperty("ngIf", ctx.showText && ctx.ref.shareButton);
ɵngcc0.ɵɵadvance(1);
ɵngcc0.ɵɵproperty("ngIf", ctx.showCount && ctx.shareCount);
} }, directives: [ɵngcc1.ShareDirective, ɵngcc2.NgIf, ɵngcc3.FaIconComponent], pipes: [ɵngcc1.ShareCountPipe], styles: [".sb-button, .sb-group{display:inline-flex;align-items:flex-start} .sb-group{flex-wrap:wrap} .sb-button{margin:.3125em} .sb-wrapper{font-size:inherit;cursor:pointer;position:relative;outline:0;min-width:4.125em;height:2.5em;border:none;border-radius:1px;padding:0;line-height:2.571em;background-color:transparent} .sb-wrapper .sb-count, .sb-wrapper .sb-icon, .sb-wrapper .sb-text{display:flex;align-items:center;justify-content:center;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none} .sb-wrapper .sb-inner{display:flex;flex:1;width:100%;height:100%} .sb-wrapper .sb-content{display:flex;height:100%;width:100%} .sb-wrapper .sb-text{padding:0 .7em;flex:1;height:100%;white-space:nowrap} .sb-wrapper .sb-icon{text-align:center;width:100%;height:100%;font-size:1.2em;min-width:2em} .sb-wrapper .sb-count{font-size:.9em;padding:0 .7em} .sb-wrapper .sb-count, .sb-wrapper .sb-text{font-weight:700} .sb-show-text .sb-icon{width:2em} .sb-show-count{min-width:5.333em}"], changeDetection: 0 });

**Comment by MurhafSousli** [comment] 2020-04-09 13:16
@cervelliriccardo that huge chunk of text is not useful, please add reproduction using [the beta version stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-v8?file=src/app/app.module.ts)

**Comment by sameretto** [comment] 2020-04-09 13:55
@MurhafSousli using the beta I get this: 
failed to compile.
./node_modules/ngx-sharebuttons/__ivy_ngcc__/fesm5/ngx-sharebuttons-icons.js 42:16-29
"export 'FaIconLibrary' was not found in '@fortawesome/angular-fontawesome'

**Comment by MurhafSousli** [comment] 2020-04-09 14:59
@sameretto indeed!

**Comment by fromage9747** [comment] 2020-04-10 10:24
Well, this is disappointing.  I upgraded to v8 beta and I am still getting the same issue.  Can anyone confirm that the beta release has fixed the issue in their app?

**Comment by crooksey** [comment] 2020-04-20 13:13
I can confirm this is fixed in the Beta, thanks.

**Comment by chhaymenghong** [comment] 2020-04-21 07:23
very nice. confirmed it is fixed

**Comment by schankam** [comment] 2020-05-03 15:34
Confirming that the beta works for me.

**Comment by karincayazilim** [comment] 2020-05-04 12:18
help please angular  9

**Comment by fromage9747** [comment] 2020-05-04 12:54
@karincayazilim try and replicate what you are trying to do in a stackblitz example. You will locate the issue whilst doing it. That is what I did and it helped me.

**Closed** 2020-05-31 19:25 UTC
Labels: @ngx-share/button, @ngx-share/buttons, bug

**Comment by Xplosive06** [comment] 2020-06-01 09:21
Hi, I'm using the beta version 8, but when I import the ShareIconsModule I'm getting :

`core.js:4117 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(BlogContentModule)[ShareIconsModule -> InjectionToken SHARE_BUTTONS_ICONS -> InjectionToken SHARE_BUTTONS_ICONS -> InjectionToken SHARE_BUTTONS_ICONS -> InjectionToken SHARE_BUTTONS_ICONS]: 
  NullInjectorError: No provider for InjectionToken SHARE_BUTTONS_ICONS!`

My code : 

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { BlogContentComponent } from './blog-content.component';
import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';
import { NgBusyModule } from 'ng-busy';
import { ShareIconsModule } from 'ngx-sharebuttons/icons';

export const routes = [
  { path: '', component: BlogContentComponent, pathMatch: 'full'  }
];

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild([
      {path: '', component: BlogContentComponent}
    ]),
    ShareButtonsModule,
    NgBusyModule,
    ShareIconsModule
  ],
  declarations: [
    BlogContentComponent
  ]
})
export class BlogContentModule { }`



Any idea?
