### ISSUE TITLE
Sharebuttons show error with universal

### ISSUE THREAD

**Issue by andy200486** [MurhafSousli/ngx-sharebuttons#370] opened 2019-01-21 10:41 UTC
#### What is the current behavior?
`ERROR TypeError: Cannot read property 'type' of undefined`
The problem seems to be at this line
`el.nativeElement.style.setProperty('--button-color', '#FF6651');`
#### Which versions are you using for the following packages?

Angular:7.1.4
Angular CDK:7.2.1
Angular CLI:7.1.4
Angular-fontawesome:0.3.0
Share buttons:7.1.1

#### Is there anything else we should know?
I'm facing issues with your module when I use server side rendering.
Could you help me ?

Thanks

**Comment by MurhafSousli** [comment] 2019-01-23 10:53
`el.nativeElement.style.setProperty('--button-color', '#FF6651');` is probably not the cause

**Comment by schankam** [comment] 2019-02-11 04:47
Mhh, I just installed this module and I am using Universal, I don't have any issues on my side. Using these versions of Universal modules:

    "@ng-toolkit/universal": "^1.1.50",
    "@nguniversal/common": "^7.1.0",
    "@nguniversal/express-engine": "^7.1.0",
    "@nguniversal/module-map-ngfactory-loader": "^7.1.0",

**Comment by MurhafSousli** [comment] 2019-02-11 04:52
@schankam Thanks for the feedback, closing as a false issue

**Closed by MurhafSousli** 2019-02-11 04:52 UTC
Labels: invalid
