### ISSUE TITLE
Export 'FontAwesomeModule' was not found in '@fortawesome/angular-fontawesome'

### ISSUE THREAD

**Issue by caeb92** [MurhafSousli/ngx-sharebuttons#307] opened 2018-06-23 22:38 UTC
Hello everyone :eyes: , I'm trying to install Share Button Component but I get an warning and the project can't compile

```
### Install process

npm i -S @ngx-share/core @ngx-share/button

npm i -S @fortawesome/fontawesome-svg-core @fortawesome/angular-fontawesome @fortawesome/free-solid-svg-icons @fortawesome/free-brands-svg-icons


+ @fortawesome/fontawesome-svg-core@1.2.0
+ @fortawesome/free-brands-svg-icons@5.1.0
+ @fortawesome/free-solid-svg-icons@5.1.0
+ @fortawesome/angular-fontawesome@0.1.0
```
```
### Error msg
WARNING in ./node_modules/@ngx-share/button/fesm5/ngx-share-button.js
190:33-50 "export 'FontAwesomeModule' was not found in '@fortawesome/angular-fontawesome'

### Console error

Uncaught Error: Unexpected value 'undefined' imported by the module 'ShareButtonModule'

```

### ng -v

Angular CLI: 6.0.8
Node: 10.3.0
OS: win32 x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

angular-devkit/architect         0.6.8
angular-devkit/build-angular     0.6.8
angular-devkit/build-optimizer   0.6.8
angular-devkit/core              0.6.8
angular-devkit/schematics        0.6.8
angular/cdk                      6.2.1
angular/cli                      6.0.8
angular/flex-layout              6.0.0-beta.15
angular/material                 6.2.1
angular/pwa                      0.6.8
ngtools/webpack                  6.0.8
schematics/angular               0.6.8
schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by MurhafSousli** [comment] 2018-06-23 23:09
@caeb92 duplicate of #303, #306. Get the latest version of Angular FontAwesome 

`npm i -S @fortawesome/angular-fontawesome@0.1.0-10`

**Closed by MurhafSousli** 2018-06-23 23:09 UTC
