### ISSUE TITLE
Update for @fortawesome/angular-fontawesome 0.1.0

### ISSUE THREAD

**Issue by pulsejet** [MurhafSousli/ngx-sharebuttons#306] opened 2018-06-23 18:30 UTC
Works with `0.1.0-10`, broken for latest `0.1.0`

**Comment by MurhafSousli** [comment] 2018-06-23 21:29
That's right, `@fortawesome/angular-fontawesome@0.1.0` is broken, duplicate of #303

**Closed by MurhafSousli** 2018-06-23 21:29 UTC

**Comment by pulsejet** [comment] 2018-06-23 22:00
Thanks for the quick reply! This library you are maintaining is truly wonderful :)

**Comment by MurhafSousli** [comment] 2018-06-23 23:08
@pulsejet  Thank you!
