### ISSUE TITLE
Adding sharebutton has increased build time from 3 minutes to 11 minutes.

### ISSUE THREAD

**Issue by scalamill** [MurhafSousli/ngx-sharebuttons#279] opened 2018-05-19 07:53 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
 Linux (Ubuntu) 18.04

**Comment by MurhafSousli** [comment] 2018-05-19 15:19
3 minutes before you add the share buttons! it seems that you have a problem in your project

**Comment by scalamill** [comment] 2018-05-19 15:58
As I add sharebuttonmodule.forRoot(), it started to hang. I just skipped
--prod flag to make it fast.

**Comment by MurhafSousli** [comment] 2018-05-19 16:11
It can be a problem with your build system. I am going to close this as it doesn't fill the issue template. If you still believe it is caused by this plugin, submit a new issue and fill the template with the versions you are using or try to reproduce the issue so I can look into it.

**Closed by MurhafSousli** 2018-05-19 16:11 UTC
