### ISSUE TITLE
WhatsApp sharing does not work on desktop 

### ISSUE THREAD

**Issue by rynx91** [MurhafSousli/ngx-sharebuttons#441] opened 2020-04-21 09:12 UTC
I'm using "@ngx-share/button": "^7.1.4".
The Whatsapp sharing does not work on desktop, except for chrome.
Here is the screenshot of the error screen in Firefox.
I have tested on Chrome, Firefox, Safari and Opera, and it only works on Chrome so far.
https://murhafsousli.github.io/ngx-sharebuttons/#/share-buttons-component

<img width="793" alt="image" src="https://user-images.githubusercontent.com/6939473/79847919-f8efa280-83f2-11ea-8473-9998934498a9.png">

**Comment by MurhafSousli** [comment] 2020-04-21 12:19
It works well for me on desktop!

here is firefox screenshot:

<img width="1102" alt="Screenshot 2020-04-21 at 14 18 25" src="https://user-images.githubusercontent.com/8130692/79865136-f97c3f00-83da-11ea-894d-375f73fa8cab.png">

And here is safari screenshot:
<img width="1426" alt="Screenshot 2020-04-21 at 14 11 40" src="https://user-images.githubusercontent.com/8130692/79864638-08aebd00-83da-11ea-80db-61b523458f2d.png">

**Comment by rynx91** [comment] 2020-04-21 12:51
I did not put my browser in mobile mode, but still seeing the same error.

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/6939473/79867981-d1f49900-8411-11ea-89de-426c0388d3c1.png">

**Comment by rynx91** [comment] 2020-04-21 12:53
I did not put my browser in mobile mode, but still seeing the same error.

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/6939473/79868179-1e3fd900-8412-11ea-97fa-8b58cd080deb.png">

**Comment by rynx91** [comment] 2020-04-22 06:23
It seems like it redirected to the desktop link first(less than 1 second), then to the mobile sharing link.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6939473/79947380-78897a00-84a4-11ea-9e8a-b58603281cc7.png">

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/6939473/79947468-9820a280-84a4-11ea-885f-58dbdbae6f2a.png">

**Comment by rynx91** [comment] 2020-04-23 08:15
@MurhafSousli I found the solution for this issue, which is to change the desktop share link for WhatsApp to: https://web.whatsapp.com/send?

**Comment by ruandeveloper** [comment] 2020-05-13 23:54
the url https://wa.me/ not work anymore! 
**### Use https://api.whatsapp.com for desktop**

**Comment by ruandeveloper** [comment] 2020-05-14 01:14
#450

**Comment by pierresigwalt** [comment] 2020-05-20 01:58
Hi, So what is the fixed for this? Is it to disable it on Desktop

**Comment by MurhafSousli** [comment] 2020-05-20 15:26
Upgrade to latest version v8

**Comment by pierresigwalt** [comment] 2020-05-21 00:35
Hi,

I may have miss something but don't think it come from the librairie. I follow the steps from what's app screen, the application is opening correctly however the link is not share afterwards. Do we need to do something else? I used the sample above from MurhafSousli

**Comment by catchshyam** [comment] 2020-05-21 06:30
Thanks.

> Upgrade to latest version v8 beta, it is working here https://stackblitz.com/edit/ngx-sharebuttons-v8

The stackblitz app still does not work as intended. Clicking on whatsapp link just opens whatsapp web on a new tab (earlier it used to be on a pop out window) but does not initiate the message.

**Comment by MurhafSousli** [comment] 2020-05-21 18:09
@catchshyam It seems that you need to add a description `<share-buttons description=" "></share-buttons>`, I will make it work without adding description in the next release

**Comment by catchshyam** [comment] 2020-05-22 09:09
@MurhafSousli Yes I figured out after going through the source code. Thanks for taking the timeout to reply

**Comment by MurhafSousli** [comment] 2020-05-23 15:36
In v8.0.0-beta.3 it will work without specifying the `description` parameter, closing...

**Closed by MurhafSousli** 2020-05-23 15:36 UTC
