### ISSUE TITLE
change title, url for facebook

### ISSUE THREAD

**Issue by akdenme** [MurhafSousli/ngx-sharebuttons#275] opened 2018-05-07 08:13 UTC
hi, can this change the url, title, and description for facebook? 

i already try it.. for others sosial can change but not for facebook..

**Comment by MurhafSousli** [comment] 2018-05-07 13:00
No, it is mentioned in the docs, only the URL can be set for facebook. duplicate of #149

**Closed by MurhafSousli** 2018-05-07 13:00 UTC
