### ISSUE TITLE
Facebook sharing directive not working: Parameter 'href' should represent a valid URL

### ISSUE THREAD

**Issue by blasco** [MurhafSousli/ngx-sharebuttons#436] opened 2020-04-09 18:59 UTC
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
The expected behavior is to share the current url in Facebook

#### What is the current behavior?
The sharing window appears but has an error message stating:
```
Parameter 'href' should represent a valid URL
```

![Screenshot_2020-04-09_20-59-31](https://user-images.githubusercontent.com/3214400/78930866-180e3c00-7aa5-11ea-9f94-8bbfee6b3f10.png)

#### Which versions are you using for the following packages?

    "@angular/core": "~8.2.14",

    "@angular/cdk": "^9.2.0",

    "@ngx-share/core": "^7.1.4",

**Comment by blasco** [comment] 2020-04-09 19:03
Ok, I found the error. It was very stupid... I'm testing on my local machine so obviously the link is wrong...

**Comment by blasco** [comment] 2020-04-09 19:16
I'm trying to define the url but it doesn't seem to work:

```
              <button 
                 shareButton="facebook"
                 [url]="'www.test.com'" 
               >
                 Share
              </button>
```

Am I doing something wrong here?

**Comment by MurhafSousli** [comment] 2020-04-11 17:45
Can you reproduce the issue in [stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-v8)?

**Comment by MurhafSousli** [comment] 2020-04-11 17:52
duplicate of #437

**Closed by MurhafSousli** 2020-04-11 17:52 UTC
