### ISSUE TITLE
@FortAwesome/angular-fontawesome dependency has deprecated

### ISSUE THREAD

**Issue by Rosseyn** [MurhafSousli/ngx-sharebuttons#416] opened 2019-11-12 20:01 UTC
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
No warnings/errors.

#### What is the current behavior?
Error in browser log appears:

FontAwesome: Global icon library is deprecated. Consult https://github.com/FortAwesome/angular-fontawesome/blob/master/UPGRADING.md for the migration instructions.

#### What are the steps to reproduce?
Use library.

#### What is the use-case or motivation for changing an existing behavior?
Hard referencing a deprecated file that's can lead to future issues and looks bad in the log.

#### Which versions are you using for the following packages?

Angular: 8.0.3
Angular CDK: 8.2.3
Angular CLI: 8.0.4
Angular-fontawesome: 0.5.0
Share buttons: 7.1.4

**Comment by abubakar491** [comment] 2019-12-12 07:48
Did you find any solution to this?

**Comment by MurhafSousli** [comment] 2020-04-07 11:15
Duplicate of #418 , let's track it there

**Closed by MurhafSousli** 2020-04-07 11:15 UTC
