### ISSUE TITLE
Directly importing icons in ShareButtonsModule.withConfig does not work

### ISSUE THREAD

**Issue by paya-cz** [MurhafSousli/ngx-sharebuttons#474] opened 2020-07-22 10:37 UTC
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

Icons imported directly from FontAwesome render properly.

```
import { faFacebookSquare } from '@fortawesome/free-brands-svg-icons/faFacebookSquare';
const shareProp = {
  facebook: {
    icon: faFacebookSquare
  }
};
@NgModule({
  imports: [
    ShareButtonsModule.withConfig({ prop: shareProp })
  ]
})
```

The code above is the last example at https://ngx-sharebuttons.netlify.app/#/icons

#### What is the current behavior?

The icons imported directly do not have any effect.

#### What are the steps to reproduce?

Use the code example from https://ngx-sharebuttons.netlify.app/#/icons
and change Facebook icon to some random FontAwesome icon. Do not import ShareIconsModule.

Use this to listen to config and see nothing gets changed. The facebook icon stays as `["fab", "facebook-f"]`

```
    constructor(
        private readonly _test: ShareService,
    ) {
        this._test.config$.subscribe(config => {
            console.log('ShareService', config);
        })
    }
```

#### Which versions are you using for the following packages?

Angular: 10.0.4
Angular CDK: 10.0.2
Angular CLI: 10.0.3
Angular-fontawesome: 0.7.0
Share buttons: 8.0.0

#### Is there anything else we should know?

The issue is caused by utils.ts/mergeDeep:

https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/utils.ts#L15

facebook.icon is initialized by default to an array, and then a merge against IconDefinition from FontAwesome is attempted. The mergeDeep does not handle the case when target prop is an array and source prop is an object. The branch https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/utils.ts#L23 is taken and mergeDeep is called on line https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/utils.ts#L27 with first param being an array, second param being IconDefinition object.

**Comment by MurhafSousli** [comment] 2020-07-22 23:04
Can you add a stackblitz reproduction to the issue please?

**Comment by paya-cz** [comment] 2020-07-23 05:34
I tried, but I keep getting this error when attempting to reproduce in stackblitz:

```
ngcc failed to run on ngx-sharebuttons@8.0.0, @fortawesome/angular-fontawesome@0.7.0.
```

I created a local reproduction instead and that one starts fine (and reproduces the bug, see app module).

[sharebuttonsbug.zip](https://github.com/MurhafSousli/ngx-sharebuttons/files/4963996/sharebuttonsbug.zip)

**Comment by MurhafSousli** [comment] 2020-07-25 23:53
Try to reproduce it here please https://stackblitz.com/edit/ngx-sharebuttons

**Comment by paya-cz** [comment] 2020-07-27 05:05
Here: https://stackblitz.com/edit/ngx-sharebuttons-rseu2k

**Comment by yonatann** [comment] 2020-10-23 21:43
A workaround for the issue can be done by adding this to your `tsconfig.json`
```
"compilerOptions": {
   "skipLibCheck": true
}
```

**Comment by MurhafSousli** [comment] 2020-10-29 20:35
So, strangely the passed icon object is being ignored when being set in config in the function `mergeDeep()` in https://github.com/MurhafSousli/ngx-sharebuttons/blob/ef11f81200dab10fdf10f664303f99a2617f4bf5/projects/ngx-sharebuttons/src/lib/utils.ts#L15

I spent sometime debugging this, but couldn't find the reason or an alternative solution.

I removed this from the docs, using the icon name instead, and import the icon as mentioned in https://ngx-sharebuttons.netlify.app/#/icons


Closing....

**Closed by MurhafSousli** 2020-10-29 20:35 UTC
