### ISSUE TITLE
ERROR in Cannot resolve type entity i3.FontAwesomeModule to symbol

### ISSUE THREAD

**Issue by Thennam-Pandian** [MurhafSousli/ngx-sharebuttons#557] opened 2021-08-23 15:50 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
1.npm i  @angular/cdk
npm i ngx-sharebuttons

//font install
npm i @fortawesome/fontawesome-svg-core @fortawesome/angular-fontawesome @fortawesome/free-solid-svg-icons @fortawesome/free-brands-svg-icons

2.

#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- ngx-sharebuttons:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment] 2021-08-23 19:25
closing as does not follow the template issue.

**Closed by MurhafSousli** 2021-08-23 19:25 UTC
Labels: invalid

**Comment by timofeysie** [comment] 2021-09-22 17:48
Looks like a valid issue:  I am seeing this: Error: Cannot resolve type entity i1.FontAwesomeModule to symbol.

Template following looks good to me @Thennam-Pandian

**Comment by MurhafSousli** [comment] 2021-09-23 22:56
I need more info, versions, reproduction, I cannot help if I don't see the error! it could be related with your project setup, try installing it in a new project using the CLI and check if it fails.
