### ISSUE TITLE
problems with the angular translate component

### ISSUE THREAD

**Issue by janixy91** [MurhafSousli/ngx-sharebuttons#157] opened 2017-09-26 07:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

hello!, 

I am using this library to translate an app:
https://www.npmjs.com/package/ng2-translate

But, if use the library for translating the title to share in twitter, the title is translated correctly but the url that is written is the browser's current url instead of the one that is sent through the parameter sbUrl

`
  <button shareButton="twitter" [sbTitle]="'Hemos conseguido ayudar a'" [sbUrl]="'https://github.com'" [sbTags]="['juegaEnFamilia']"> <i class="fa fa-twitter"></i>  </button>`

![captura de pantalla 2017-09-26 a las 9 34 31](https://user-images.githubusercontent.com/6758330/30848082-2f2f12a6-a29e-11e7-8cd9-38e40be1fe34.png)

this one was ok, but with the translated text: 

`  <button shareButton="twitter" [sbTitle]="'flopi-unlocked-congrats' | translate" [sbUrl]="'https://github.com'" [sbTags]="['juegaEnFamilia']"> <i class="fa fa-twitter"></i>  </button>`

![captura de pantalla 2017-09-26 a las 9 35 16](https://user-images.githubusercontent.com/6758330/30848093-3ca5056c-a29e-11e7-9200-6ff9bf328cf3.png)

the title is ok, but the url is not the good one

thanks !

**Comment by MurhafSousli** [comment] 2017-09-26 09:25
Hi @janixy91, I just tested your code with [this stackblitz](https://stackblitz.com/edit/angular-n7jm4q?file=app%2Fapp.component.html), It seems to be working fine!
Can you try to reproduce the problem there?

**Comment by janixy91** [comment] 2017-09-26 11:59
Hi, 

thanks for your reply, 

in this example it´s working correctly, but I copy this button in my app and it doesn´t work good, 

i have just create one basic project and it fails, I think that it fails because I use the asyncronoush translate,

I attach my basic project, and in the service, in the function "loadLanguages", I have put the two ways, he asyncronoush ways fails, the another one it´s ok

thanks for your help! :)
[testShare.zip](https://github.com/MurhafSousli/ngx-sharebuttons/files/1333016/testShare.zip)

**Comment by MurhafSousli** [comment] 2017-09-27 21:43
Hi @janixy91, I won't be able to help you with the attached project. but I recommend you to use [@ngx-translate/core](https://github.com/ngx-translate/core) instead, it might solve your issue.

Closing this as not related to this package. but feel free to continue the discussion :)

**Closed by MurhafSousli** 2017-09-27 21:43 UTC
