### ISSUE TITLE
Instagram share

### ISSUE THREAD

**Issue by mind84** [MurhafSousli/ngx-sharebuttons#244] opened 2018-03-26 19:34 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### Desired functionality

Hi, simply I'm wondering if you are implementing Instagram sharing button, or if you have planned it for the future 

thanks in advance

**Comment by MurhafSousli** [comment] 2018-03-27 00:58
Duplicate of #244
Instagram does not have a share button

**Closed by MurhafSousli** 2018-03-27 00:58 UTC
