### ISSUE TITLE
Why is instagram sharing not included in this ?

### ISSUE THREAD

**Issue by hinalshah91** [MurhafSousli/ngx-sharebuttons#272] opened 2018-04-30 07:31 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

**Comment by MurhafSousli** [comment] 2018-04-30 19:01
Duplicate of #244, #220, #44

**Closed by MurhafSousli** 2018-04-30 19:01 UTC
