### ISSUE TITLE
shareButton directive doesn't work on mobile screens

### ISSUE THREAD

**Issue by ildar-icoosoft** [MurhafSousli/ngx-sharebuttons#353] opened 2018-12-05 13:59 UTC
#### I am submitting a

- [x] Bug Report

I have the HTML code:
```
<span class="twitter_icon" shareButton="twitter"></span>
```
It works on desktop screens. If I click on the icon in web browser in mobile device (or in desktop Chrome with device toolbar after page refreshing) then nothing is happened.

I get this error in StackBlitz starter: https://stackblitz.com/edit/ngx-sharebuttons (in fullscreen https://ngx-sharebuttons.stackblitz.io/)
Just open device toolbar in Chrome and refresh the page

**Comment by MurhafSousli** [comment] 2018-12-07 14:50
On which phone did you test it?

**Comment by andy200486** [comment] 2018-12-10 08:17
Same for me, doesn't work on iOS with Chrome. Work perfectly on desktop but not on mobile.

**Comment by MurhafSousli** [comment] 2018-12-10 10:54
Closing as duplicate of #351

**Closed by MurhafSousli** 2018-12-10 10:54 UTC
