### ISSUE TITLE
Could not find icon (StackBlitz Attached)

### ISSUE THREAD

**Issue by randallmeeker** [MurhafSousli/ngx-sharebuttons#419] opened 2019-11-27 17:18 UTC
### I have seen this bug report before, where they did not import the icon. I beleive I am doing as the docs instruct. Using the example at the bottom of this page

https://murhafsousli.github.io/ngx-sharebuttons/#/icons

#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

Icons can be set directly

#### What is the current behavior?

When attempting to set icons directly, i get an error saying the icon can not be found

#### What are the steps to reproduce?

Here is a stackblitz

https://stackblitz.com/edit/ngx-sharebuttons-yzvkkv

And an example of my config
```
import { faFacebookF } from '@fortawesome/free-brands-svg-icons/faFacebookF';
import { faPinterestP } from '@fortawesome/free-brands-svg-icons/faPinterestP';

import { IShareButtons, ShareButtonsConfig } from '@ngx-share/core';

export const shareProp: IShareButtons = {
  facebook: {
    icon: faFacebookF
  },
  pinterest: { icon: faPinterestP }
};

export const shareConfig: ShareButtonsConfig = {
  include: ['pinterest', 'facebook'],
  prop: shareProp,
  debug: true
};
```
#### StackBlitz
![image](https://user-images.githubusercontent.com/2538537/69763882-2d0cb300-1134-11ea-8c40-a849852d6320.png)

**Comment by MurhafSousli** [comment] 2020-04-07 11:14
Duplicate of #418

**Closed by MurhafSousli** 2020-04-07 11:14 UTC
